import React from 'react';

const PrivacyPolicyPage = () => {
  return (
    <div className="bg-gray-100 text-gray-800 antialiased font-sans min-h-screen">
      <div className="container mx-auto p-4 md:p-8 lg:p-12">
        <div className="bg-white rounded-xl shadow-lg p-6 md:p-10 lg:p-16">
          <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold text-center mb-6 text-teal-600">
            Privacy Policy
          </h1>
          <p className="text-center text-sm text-gray-500 mb-8">
            **Last updated:** August 2, 2025
          </p>

          <p className="mb-6 leading-relaxed">
            This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p className="mb-8 leading-relaxed">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mt-8 mb-4 text-gray-900">
            1. Interpretation and Definitions
          </h2>

          <h3 className="text-xl md:text-2xl font-medium mt-6 mb-2 text-gray-800">
            Interpretation
          </h3>
          <p className="mb-4 leading-relaxed">
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3 className="text-xl md:text-2xl font-medium mt-6 mb-2 text-gray-800">
            Definitions
          </h3>
          <ul className="list-disc list-inside space-y-2 text-gray-700 leading-relaxed pl-4">
            <li>
              <strong className="font-bold">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
            </li>
            <li>
              <strong className="font-bold">Company</strong> (referred to as either "the Company," "We," "Us," or "Our" in this Agreement) refers to [Your Company Name].
            </li>
            <li>
              <strong className="font-bold">Service</strong> refers to the Application or Website.
            </li>
            <li>
              <strong className="font-bold">Personal Data</strong> is any information that relates to an identified or identifiable individual.
            </li>
            <li>
              <strong className="font-bold">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              <strong className="font-bold">Cookies</strong> are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.
            </li>
          </ul>

          <h2 className="text-2xl md:text-3xl font-semibold mt-8 mb-4 text-gray-900">
            2. Collecting and Using Your Personal Data
          </h2>

          <h3 className="text-xl md:text-2xl font-medium mt-6 mb-2 text-gray-800">
            Types of Data Collected
          </h3>
          <h4 className="text-lg font-semibold mt-4 mb-2 text-gray-700">
            Personal Data
          </h4>
          <p className="mb-4 leading-relaxed">
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc list-inside space-y-1 text-gray-700 leading-relaxed pl-4">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="text-lg font-semibold mt-4 mb-2 text-gray-700">
            Usage Data
          </h4>
          <p className="mb-4 leading-relaxed">
            Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <p className="mb-6 leading-relaxed">
            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </p>

          <h3 className="text-xl md:text-2xl font-medium mt-6 mb-2 text-gray-800">
            Use of Your Personal Data
          </h3>
          <p className="mb-4 leading-relaxed">
            The Company may use Personal Data for the following purposes:
          </p>
          <ul className="list-disc list-inside space-y-2 text-gray-700 leading-relaxed pl-4">
            <li>
              <strong className="font-bold">To provide and maintain our Service</strong>, including monitoring the usage of our Service.
            </li>
            <li>
              <strong className="font-bold">To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
            </li>
            <li>
              <strong className="font-bold">To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
            </li>
            <li>
              <strong className="font-bold">To provide You</strong> with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
            </li>
            <li>
              <strong className="font-bold">To manage Your requests:</strong> To attend and manage Your requests to Us.
            </li>
            <li>
              <strong className="font-bold">For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
            </li>
            <li>
              <strong className="font-bold">For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service, products, services, marketing, and your experience.
            </li>
          </ul>

          <h2 className="text-2xl md:text-3xl font-semibold mt-8 mb-4 text-gray-900">
            3. Security of Your Personal Data
          </h2>
          <p className="mb-6 leading-relaxed">
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mt-8 mb-4 text-gray-900">
            4. Children's Privacy
          </h2>
          <p className="mb-6 leading-relaxed">
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mt-8 mb-4 text-gray-900">
            5. Links to Other Websites
          </h2>
          <p className="mb-4 leading-relaxed">
            Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
          </p>
          <p className="mb-6 leading-relaxed">
            We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mt-8 mb-4 text-gray-900">
            6. Changes to this Privacy Policy
          </h2>
          <p className="mb-4 leading-relaxed">
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
          </p>
          <p className="mb-6 leading-relaxed">
            We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mt-8 mb-4 text-gray-900">
            7. Contact Us
          </h2>
          <p className="mb-4 leading-relaxed">
            If you have any questions about this Privacy Policy, You can contact us:
          </p>
          <ul className="list-disc list-inside space-y-1 text-gray-700 leading-relaxed pl-4">
            <li>By email: [Your Contact Email]</li>
            <li>By visiting this page on our website: [Your Website Contact Page URL]</li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicyPage;
